/**
 * Auto-generated by `pnpm gen:types` (Supabase CLI). Do not edit by hand.
 *
 * Run:
 *   supabase start
 *   pnpm db:migrate
 *   pnpm gen:types
 */

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
