"""PDF structural fingerprinting.

Bank-issued PDFs and AI-generated PDFs have very different structural
fingerprints. This module inspects metadata, fonts, content streams and the
text-layer / raster ratio without ever asking an LLM, so we always have a
deterministic forensic signal even when the network is down.

All checks are best-effort; if a check cannot run (missing dependency, parse
error, non-PDF file), it returns an empty signal list rather than failing the
caller.
"""

from __future__ import annotations

from typing import Any

# Producer / creator strings that indicate the PDF was generated by an
# AI tool, an HTML-to-PDF converter, or a screenshot-to-PDF flow rather than a
# bank's reporting system. Matched case-insensitively as a substring.
SUSPICIOUS_PRODUCERS: tuple[str, ...] = (
    "chatgpt",
    "openai",
    "claude",
    "anthropic",
    "gemini",
    "midjourney",
    "stable diffusion",
    "wkhtmltopdf",
    "pdfkit",
    "weasyprint",
    "puppeteer",
    "headless chrome",
    "playwright",
    "html2pdf",
    "jspdf",
    "reportlab",   # very common in AI scripts but also legitimate; medium severity
    "tcpdf",
    "fpdf",
    "cairo",
    "skia",        # browser print
    "quartz pdfcontext",  # macOS screenshot-to-PDF
    "preview",     # macOS Preview, often used to re-export edited PDFs
)

# Producers that are typical for real bank reporting systems / industrial
# document generators. Their presence is a (weak) trust signal.
TRUSTED_PRODUCER_HINTS: tuple[str, ...] = (
    "adobe",
    "acrobat",
    "ghostscript",
    "ibm",
    "oracle",
    "sap",
    "crystal reports",
    "jasperreports",
    "itext",
    "microsoft",
    "openoffice",
    "libreoffice",
    "antenna house",
    "fop",
    "prince",
    "xep",
)

# Font families that appear in nearly every legitimate Tunisian bank statement.
# AI-generated PDFs often use a single non-banking font (e.g. Times-Roman).
BANKING_FONT_HINTS: tuple[str, ...] = (
    "helvetica",
    "arial",
    "calibri",
    "verdana",
    "times",
    "courier",
    "cambria",
    "tahoma",
    "segoe",
)


def analyse_pdf(file_bytes: bytes, mime_type: str) -> list[dict[str, Any]]:
    """Return a list of typed forensic signals from PDF structural inspection.

    Each signal: {type, severity, detail, evidence, source: "pdf_structure"}.
    Empty list = no PDF, parse failed, or nothing suspicious detected.
    """
    if mime_type != "application/pdf":
        return []

    signals: list[dict[str, Any]] = []
    try:
        import fitz  # PyMuPDF
    except ImportError:
        return []

    try:
        doc = fitz.open(stream=file_bytes, filetype="pdf")
    except Exception:
        return [
            {
                "type": "pdf_unparseable",
                "severity": "medium",
                "detail": "PDF could not be opened with PyMuPDF — file may be corrupt or encrypted.",
                "evidence": {},
                "source": "pdf_structure",
            }
        ]

    try:
        signals.extend(_metadata_signals(doc))
        signals.extend(_text_layer_signals(doc, len(file_bytes)))
        signals.extend(_font_signals(doc))
        signals.extend(_content_stream_signals(doc, len(file_bytes)))
    finally:
        doc.close()

    return signals


# ---------------------------------------------------------------------------
# Metadata
# ---------------------------------------------------------------------------


def _metadata_signals(doc: Any) -> list[dict[str, Any]]:
    md = doc.metadata or {}
    producer = (md.get("producer") or "").strip()
    creator = (md.get("creator") or "").strip()
    title = (md.get("title") or "").strip()
    blob = f"{producer} {creator} {title}".lower()

    out: list[dict[str, Any]] = []

    # No producer at all is suspicious for a bank PDF
    if not producer and not creator:
        out.append(
            {
                "type": "pdf_missing_producer",
                "severity": "medium",
                "detail": "PDF has no producer or creator metadata — uncommon for bank reporting systems.",
                "evidence": {"producer": producer, "creator": creator},
                "source": "pdf_structure",
            }
        )

    matched = [hint for hint in SUSPICIOUS_PRODUCERS if hint in blob]
    if matched:
        # Tier severity: AI tool names are critical, HTML/screenshot converters
        # are high, generic libraries (reportlab/macOS preview) are medium.
        if any(
            x in matched
            for x in (
                "chatgpt",
                "openai",
                "claude",
                "anthropic",
                "gemini",
                "midjourney",
                "stable diffusion",
            )
        ):
            severity = "critical"
        elif any(
            x in matched
            for x in (
                "wkhtmltopdf",
                "pdfkit",
                "weasyprint",
                "puppeteer",
                "headless chrome",
                "playwright",
                "html2pdf",
                "jspdf",
                "skia",
            )
        ):
            severity = "high"
        else:
            severity = "medium"
        out.append(
            {
                "type": "pdf_suspicious_producer",
                "severity": severity,
                "detail": (
                    f"PDF was produced by '{producer or creator}', which is associated "
                    f"with AI generation or HTML-to-PDF conversion rather than a bank "
                    f"reporting system."
                ),
                "evidence": {
                    "producer": producer,
                    "creator": creator,
                    "matched_signatures": matched,
                },
                "source": "pdf_structure",
            }
        )

    return out


# ---------------------------------------------------------------------------
# Text-layer / raster ratio
# ---------------------------------------------------------------------------


def _text_layer_signals(doc: Any, file_size_bytes: int) -> list[dict[str, Any]]:
    """A real bank PDF has machine-encoded text on every page; AI screenshots
    are pure raster (one large image per page, no text layer)."""
    out: list[dict[str, Any]] = []

    page_count = len(doc)
    if page_count == 0:
        return [
            {
                "type": "pdf_empty",
                "severity": "high",
                "detail": "PDF contains zero pages.",
                "evidence": {},
                "source": "pdf_structure",
            }
        ]

    pages_with_text = 0
    pages_image_only = 0
    total_text_chars = 0

    for page in doc:
        try:
            text = page.get_text() or ""
            text_len = len(text.strip())
            total_text_chars += text_len

            try:
                images = page.get_images()
            except Exception:
                images = []

            if text_len >= 50:
                pages_with_text += 1
            elif images:
                pages_image_only += 1
        except Exception:
            continue

    text_coverage = pages_with_text / page_count

    # Pure raster PDF (every page is just an image with no extractable text)
    # — strong signal of a screenshot, photo, or AI-generated render.
    if pages_with_text == 0 and pages_image_only > 0:
        out.append(
            {
                "type": "pdf_no_text_layer",
                "severity": "high",
                "detail": (
                    f"All {page_count} page(s) contain only embedded images with no "
                    f"machine-readable text layer. Genuine bank PDFs always include a "
                    f"text layer; this looks like a screenshot or photo."
                ),
                "evidence": {
                    "page_count": page_count,
                    "pages_with_text": pages_with_text,
                    "pages_image_only": pages_image_only,
                },
                "source": "pdf_structure",
            }
        )
    elif text_coverage < 0.5 and page_count > 1:
        out.append(
            {
                "type": "pdf_partial_text_layer",
                "severity": "medium",
                "detail": (
                    f"Only {pages_with_text}/{page_count} pages have a usable text layer. "
                    f"Mixed scanned/digital statements are unusual."
                ),
                "evidence": {
                    "page_count": page_count,
                    "pages_with_text": pages_with_text,
                    "text_coverage": round(text_coverage, 2),
                },
                "source": "pdf_structure",
            }
        )

    # File-size vs text ratio: a 5 MB PDF with 200 chars of text is almost
    # certainly a high-resolution screenshot or photo of a fake document.
    if file_size_bytes > 1_000_000 and total_text_chars < 200 and page_count <= 3:
        out.append(
            {
                "type": "pdf_size_text_mismatch",
                "severity": "medium",
                "detail": (
                    f"File is {file_size_bytes // 1024} KB but contains only "
                    f"{total_text_chars} characters of text — consistent with a "
                    f"high-resolution image masquerading as a statement."
                ),
                "evidence": {
                    "file_size_bytes": file_size_bytes,
                    "total_text_chars": total_text_chars,
                    "page_count": page_count,
                },
                "source": "pdf_structure",
            }
        )

    return out


# ---------------------------------------------------------------------------
# Fonts
# ---------------------------------------------------------------------------


def _font_signals(doc: Any) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    fonts: set[str] = set()
    embedded_count = 0
    non_embedded_count = 0

    for page in doc:
        try:
            for f in page.get_fonts(full=True):
                # PyMuPDF tuple shape: (xref, ext, type, basefont, name, encoding, ...)
                if len(f) >= 4:
                    base_font = (f[3] or "").lower()
                    if base_font:
                        fonts.add(base_font)
                if len(f) >= 2 and f[1]:  # ext present → embedded
                    embedded_count += 1
                else:
                    non_embedded_count += 1
        except Exception:
            continue

    if not fonts:
        # No fonts at all → likely image-only PDF (already flagged in text layer
        # check). Don't double-count here.
        return out

    has_banking_font = any(
        any(hint in font_name for hint in BANKING_FONT_HINTS) for font_name in fonts
    )

    # Single-font PDFs are very rare in bank statements (headers usually mix
    # bold/regular families). One font + no banking-typical name = suspicious.
    if len(fonts) <= 1 and not has_banking_font:
        out.append(
            {
                "type": "pdf_atypical_font_set",
                "severity": "medium",
                "detail": (
                    f"PDF uses a single non-banking font ({', '.join(sorted(fonts))}). "
                    f"Bank statements typically mix Helvetica/Arial/Times variants."
                ),
                "evidence": {"fonts": sorted(fonts)},
                "source": "pdf_structure",
            }
        )

    if non_embedded_count > 0 and embedded_count == 0:
        out.append(
            {
                "type": "pdf_no_embedded_fonts",
                "severity": "low",
                "detail": (
                    "No fonts are embedded in the PDF; rendering depends on the viewer. "
                    "Banks almost always embed fonts to guarantee fidelity."
                ),
                "evidence": {
                    "embedded_count": embedded_count,
                    "non_embedded_count": non_embedded_count,
                },
                "source": "pdf_structure",
            }
        )

    return out


# ---------------------------------------------------------------------------
# Content stream sanity
# ---------------------------------------------------------------------------


def _content_stream_signals(doc: Any, file_size_bytes: int) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    page_count = len(doc)

    # Average bytes-per-page heuristic: a bank statement is typically
    # 30-200 KB/page; AI screenshot pages can be megabytes.
    if page_count > 0:
        per_page = file_size_bytes / page_count
        if per_page > 1_500_000:
            out.append(
                {
                    "type": "pdf_oversized_pages",
                    "severity": "low",
                    "detail": (
                        f"Average page weight is {int(per_page / 1024)} KB — far above "
                        f"typical bank reports (~50-200 KB/page)."
                    ),
                    "evidence": {
                        "bytes_per_page": int(per_page),
                        "page_count": page_count,
                    },
                    "source": "pdf_structure",
                }
            )

    # Encryption is generally fine for banks but unusual for an end-user
    # uploading a "their own" statement — log as low.
    try:
        if doc.is_encrypted:
            out.append(
                {
                    "type": "pdf_encrypted",
                    "severity": "low",
                    "detail": "PDF is encrypted; some forensic checks may be limited.",
                    "evidence": {},
                    "source": "pdf_structure",
                }
            )
    except Exception:
        pass

    return out
