"""Multi-page Claude Vision ensemble.

The previous Layer-1 only showed Claude the first page of a PDF, so an
attacker only needed one convincing page. This module renders every page (up
to a cap), runs both the existing forensic prompt AND an AI-generation prompt
with two different models, then aggregates per-page votes into a single result.

A page "votes" failure if either model returns passed=false OR confidence<0.5.
The ensemble fails the document if any page votes failure with a model agreement
of at least 1/2, OR more than 1/3 of pages have any failing vote.
"""

from __future__ import annotations

import base64
import logging
from typing import Any

import anthropic

from klaro_ml.settings import get_settings

logger = logging.getLogger(__name__)

MAX_PAGES = 6  # cap to control latency / cost

FORENSIC_PROMPT = """\
You are a forensic document analyst inspecting a single page from a bank
statement for signs of digital manipulation. Look for:
- Inconsistent font rendering (mixed DPI, different kerning in the same field)
- Pixel-level artifacts around amounts (copy-paste halos, resampling)
- Inconsistent background texture or colour between sections
- Misaligned text suggesting overlay editing
- Brightness or colour discontinuities in text regions
- Suspicious regularity (every amount identical, impossible round numbers)
- Anomalous watermarks, seals, or security features
- Date/timestamp inconsistencies

Return ONLY valid JSON, no markdown:
{
  "passed": <true if page looks genuine, false if any tampering>,
  "confidence": <0.0-1.0>,
  "signals": [<short strings describing each issue found, empty if none>]
}
"""

AI_GENERATION_PROMPT = """\
You are inspecting a single image to decide whether it was generated by an AI
image model (e.g. diffusion, GAN), an HTML-to-PDF screenshot of a fabricated
template, or a genuine bank scan/photograph.

Tell-tale AI-generation signs:
- Glyphs that look "right" at a glance but contain malformed characters,
  mismatched diacritics, or unstable letter widths
- Plausible-but-fictional bank logos, addresses, or account numbers
- Backgrounds with texture noise that does not match real scanner/camera output
- Tables whose alignment is too perfect (no skew, no JPEG bleed at edges)
- Repeating identical noise patterns across regions

Return ONLY valid JSON, no markdown:
{
  "passed": <true if the page appears to be a genuine bank document, false if AI-generated or screenshot of a fabricated template>,
  "confidence": <0.0-1.0>,
  "signals": [<short strings, empty if none>]
}
"""


def analyse(file_bytes: bytes, mime_type: str) -> dict[str, Any]:
    """Run the multi-page Claude Vision ensemble.

    Returns:
        {
          "available": bool,            # whether the LLM call ran
          "pages_analysed": int,
          "page_votes": [{page, model, prompt, passed, confidence, signals}],
          "signals": [aggregated typed signals],
        }
    """
    settings = get_settings()
    if not settings.ANTHROPIC_API_KEY:
        return {
            "available": False,
            "pages_analysed": 0,
            "page_votes": [],
            "signals": [],
        }

    page_images = _render_pages(file_bytes, mime_type)
    if not page_images:
        return {
            "available": False,
            "pages_analysed": 0,
            "page_votes": [],
            "signals": [],
        }

    client = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY)
    page_votes: list[dict[str, Any]] = []

    for page_index, (img_bytes, img_mime) in enumerate(page_images):
        for model_name, prompt_label, system_prompt in (
            (settings.CLAUDE_SONNET, "forensic", FORENSIC_PROMPT),
            (settings.CLAUDE_HAIKU, "ai_generation", AI_GENERATION_PROMPT),
        ):
            try:
                vote = _ask_one(client, model_name, system_prompt, img_bytes, img_mime)
            except Exception as exc:
                logger.warning("vision ensemble call failed (page %d, model %s): %s",
                               page_index + 1, model_name, exc)
                continue
            vote["page"] = page_index + 1
            vote["model"] = model_name
            vote["prompt"] = prompt_label
            page_votes.append(vote)

    return {
        "available": True,
        "pages_analysed": len(page_images),
        "page_votes": page_votes,
        "signals": _aggregate(page_votes, len(page_images)),
    }


# ---------------------------------------------------------------------------
# Per-page rendering
# ---------------------------------------------------------------------------


def _render_pages(file_bytes: bytes, mime_type: str) -> list[tuple[bytes, str]]:
    """Return a list of (bytes, mime) per page. Image inputs become a single page."""
    if mime_type.startswith("image/"):
        return [(file_bytes, mime_type)]

    if mime_type != "application/pdf":
        return []

    try:
        import fitz  # PyMuPDF
    except ImportError:
        return []

    try:
        doc = fitz.open(stream=file_bytes, filetype="pdf")
    except Exception:
        return []

    out: list[tuple[bytes, str]] = []
    try:
        for page_index in range(min(MAX_PAGES, len(doc))):
            try:
                pix = doc[page_index].get_pixmap(matrix=fitz.Matrix(2.0, 2.0))
                out.append((pix.tobytes("png"), "image/png"))
            except Exception:
                continue
    finally:
        doc.close()
    return out


# ---------------------------------------------------------------------------
# Single LLM call
# ---------------------------------------------------------------------------


def _ask_one(
    client: anthropic.Anthropic,
    model: str,
    system_prompt: str,
    image_bytes: bytes,
    image_mime: str,
) -> dict[str, Any]:
    import json

    media_type = image_mime if image_mime in (
        "image/jpeg", "image/jpg", "image/png", "image/webp", "image/gif"
    ) else "image/png"
    b64 = base64.standard_b64encode(image_bytes).decode()

    res = client.messages.create(
        model=model,
        max_tokens=512,
        system=system_prompt,
        messages=[{
            "role": "user",
            "content": [{
                "type": "image",
                "source": {"type": "base64", "media_type": media_type, "data": b64},
            }],
        }],
    )

    raw = res.content[0].text.strip()  # type: ignore[union-attr]
    if raw.startswith("```"):
        raw = "\n".join(raw.split("\n")[1:])
    if raw.endswith("```"):
        raw = raw[: raw.rfind("```")]

    try:
        parsed = json.loads(raw)
    except (json.JSONDecodeError, AttributeError):
        # Treat as a non-vote rather than a forced pass
        return {"passed": True, "confidence": 0.0, "signals": ["llm_parse_error"]}

    return {
        "passed": bool(parsed.get("passed", True)),
        "confidence": float(parsed.get("confidence", 0.5)),
        "signals": list(parsed.get("signals", []) or []),
    }


# ---------------------------------------------------------------------------
# Aggregation
# ---------------------------------------------------------------------------


def _aggregate(page_votes: list[dict[str, Any]], pages_total: int) -> list[dict[str, Any]]:
    """Roll per-page model votes into typed signals for the rule engine."""
    if not page_votes or pages_total == 0:
        return []

    signals: list[dict[str, Any]] = []

    # Count failing votes per page
    pages_with_fail: dict[int, list[dict[str, Any]]] = {}
    for v in page_votes:
        if not v.get("passed", True) or v.get("confidence", 1.0) < 0.5:
            pages_with_fail.setdefault(v["page"], []).append(v)

    # Page-level signals
    for page, fail_votes in pages_with_fail.items():
        models = sorted({v["model"] for v in fail_votes})
        all_signals: list[str] = []
        for v in fail_votes:
            all_signals.extend(v.get("signals", []))
        severity = "high" if len(models) >= 2 else "medium"
        signals.append({
            "type": "vision_page_flagged",
            "severity": severity,
            "detail": (
                f"Page {page} flagged by {len(models)} of 2 vision model(s): "
                f"{'; '.join(all_signals[:6]) if all_signals else 'no specific signals returned'}."
            ),
            "evidence": {
                "page": page,
                "models_flagging": models,
                "model_signals": all_signals[:12],
            },
            "source": "vision_ensemble",
        })

    # Document-level disagreement signal: when models disagree on the same page
    disagreements = 0
    for v in page_votes:
        peers = [
            o for o in page_votes
            if o["page"] == v["page"] and o["model"] != v["model"] and o["prompt"] == v["prompt"]
        ]
        for peer in peers:
            if peer.get("passed") != v.get("passed"):
                disagreements += 1

    if disagreements > 0:
        signals.append({
            "type": "vision_model_disagreement",
            "severity": "low",
            "detail": (
                f"{disagreements // 2} model pair(s) disagreed on whether a page is genuine. "
                f"Disagreement is itself a confidence-reducing signal."
            ),
            "evidence": {"disagreement_pairs": disagreements // 2},
            "source": "vision_ensemble",
        })

    # Fraction-of-document signal
    if pages_with_fail:
        frac = len(pages_with_fail) / pages_total
        if frac > 0.33:
            signals.append({
                "type": "vision_majority_flagged",
                "severity": "high",
                "detail": (
                    f"{len(pages_with_fail)}/{pages_total} pages were flagged by at "
                    f"least one vision model — well above the noise floor for a "
                    f"legitimate document."
                ),
                "evidence": {
                    "pages_flagged": len(pages_with_fail),
                    "pages_total": pages_total,
                    "fraction": round(frac, 2),
                },
                "source": "vision_ensemble",
            })

    return signals
